# Generated by Django 3.1.7 on 2021-05-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, default='No Generic Name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, default='No Name', max_length=200, null=True),
        ),
    ]
