# Generated by Django 3.1.7 on 2021-05-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210507_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='traces',
            field=models.CharField(default='no traces', max_length=200),
        ),
    ]
