# Generated by Django 3.1.7 on 2021-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210507_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_100g',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
