# Generated by Django 3.1.7 on 2021-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210507_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additives_tags',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergens_tags',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='countries',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, default='No Generic Name', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_ingredients_url',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_nutrition_url',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small_url',
            field=models.CharField(default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients_text',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.CharField(default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='origins',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pnns_groups_1',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pnns_groups_2',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, default='No Name', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='traces',
            field=models.CharField(default='no traces', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_quantity',
            field=models.CharField(blank=True, default=0, max_length=2000, null=True),
        ),
    ]
