# Generated by Django 3.1.7 on 2021-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210507_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='grofilters',
            name='nova_group',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grofilters',
            name='nutriscore_grade',
            field=models.CharField(blank=True, max_length=90000, null=True),
        ),
    ]
