# Generated by Django 3.1.7 on 2021-06-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210607_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grofilters',
            name='NObrand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grofilters',
            name='NOorigin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grofilters',
            name='NOpackaging',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grofilters',
            name='Supermarket',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grofilters',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grofilters',
            name='origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
